version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: captain
      POSTGRES_PASSWORD: squawkvfr
      POSTGRES_DB: flynance
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  api: &api_base
    build: ./aircraft_api
    restart: always
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      DATABASE_URL: postgresql://captain:squawkvfr@postgres:5432/flynance
    ports:
      - 8080:8080
    volumes:
      - ./aircraft_api:/app
    depends_on:
      - db
  migrations: 
    <<: *api_base
    command: python manage.py migrate
    ports: []
volumes:
  pgdata:
