version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: captain
      POSTGRES_PASSWORD: squawkvfr
      POSTGRES_DB: flynance
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  api: &api_base
    build: ./aircraft_api
    restart: always
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: postgresql://captain:squawkvfr@postgres:5432/flynance
    ports:
      - 8000:8000
    volumes:
      - ./aircraft_api:/app
    depends_on:
      - db
  migrations: 
    <<: *api_base
    restart: 'no'
    command: python manage.py migrate
    ports: []
  node:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    command: >
      sh -c "http-server dist"
  mission_match:
    build: ./mission_match
    restart: always
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - db
volumes:
  pgdata:
