version: '3.8'

services:
  api:
    ports:
      - "5677:5677"  # Debugger port
      - "5678:5678"  # Debugger port
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000"]
