# Generated by Django 5.1.1 on 2024-11-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_alter_modelscrape_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftmodel',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aircraft.engine'),
        ),
        migrations.AlterField(
            model_name='aircraftmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircraft.manufacturerscrape'),
        ),
    ]
