# Generated by Django 5.1.1 on 2024-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_rename_aircraft_aircraftlisting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftCrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_type', models.CharField(choices=[('auto', 'Auto'), ('fixed', 'Fixed'), ('float', 'Float'), ('manual', 'Manual'), ('other', 'Other'), ('ski', 'Ski'), ('skid', 'Skid')], max_length=6)),
                ('flap_type', models.CharField(choices=[('electric', 'Electric'), ('manual', 'Manual'), ('none', 'None'), ('other', 'Other')], max_length=8)),
                ('propeller_type', models.CharField(choices=[('constant_speed', 'Constant Speed'), ('fixed_pitch', 'Fixed Pitch')], max_length=24, null=True)),
                ('engine_monitor_type', models.CharField(choices=[('analog', 'Analog'), ('digital', 'Digital'), ('none', 'None')], max_length=7, null=True)),
                ('engine_count', models.IntegerField()),
                ('total_cost_of_ownership', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('total_fixed_cost', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('total_variable_cost', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('annual_inspection_cost', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('fuel_burn', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fuel_burn_cruise', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fuel_unit', models.CharField(max_length=20, null=True)),
                ('cruise_speed', models.IntegerField(null=True)),
                ('stall_speed', models.IntegerField(null=True)),
                ('ceiling', models.IntegerField(null=True)),
                ('ceiling_engine_out', models.IntegerField(null=True)),
                ('takeoff_distance', models.IntegerField(null=True)),
                ('landing_distance', models.IntegerField(null=True)),
                ('takeoff_distance_50', models.IntegerField(null=True)),
                ('landing_distance_50', models.IntegerField(null=True)),
                ('gross_weight', models.IntegerField(null=True)),
                ('empty_weight', models.IntegerField(null=True)),
                ('max_payload', models.IntegerField(null=True)),
                ('range', models.IntegerField(null=True)),
                ('rate_of_climb', models.IntegerField(null=True)),
                ('rate_of_climb_engine_out', models.IntegerField(null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=256, null=True)),
                ('engine', models.CharField(blank=True, max_length=256, null=True)),
                ('owner', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
