# Generated by Django 5.1.1 on 2024-11-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0009_aircraftcrawl_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcrawl',
            name='last_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
