"""Initial Migration

Revision ID: 74560e8bfc0c
Revises: 
Create Date: 2024-06-01 17:02:05.411006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74560e8bfc0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('fixed_gear', sa.Boolean(), nullable=False),
    sa.Column('manual_gear', sa.Boolean(), nullable=False),
    sa.Column('auto_gear', sa.Boolean(), nullable=False),
    sa.Column('manual_flaps', sa.Boolean(), nullable=False),
    sa.Column('auto_flaps', sa.Boolean(), nullable=False),
    sa.Column('no_flaps', sa.Boolean(), nullable=False),
    sa.Column('analog_em', sa.Boolean(), nullable=False),
    sa.Column('digital_em', sa.Boolean(), nullable=False),
    sa.Column('model_year_start', sa.Integer(), nullable=False),
    sa.Column('model_year_end', sa.Integer(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('total_cost_of_ownership', sa.Float(), nullable=False),
    sa.Column('total_fixed_cost', sa.Float(), nullable=False),
    sa.Column('total_variable_cost', sa.Float(), nullable=False),
    sa.Column('annual_inspection_cost', sa.Float(), nullable=False),
    sa.Column('tbo', sa.Integer(), nullable=False),
    sa.Column('fuel_burn', sa.Float(), nullable=False),
    sa.Column('fuel_burn_cruise', sa.Float(), nullable=False),
    sa.Column('fuel_capacity', sa.Float(), nullable=False),
    sa.Column('fuel_unit', sa.String(length=20), nullable=False),
    sa.Column('cruise', sa.Integer(), nullable=False),
    sa.Column('stall_speed', sa.Integer(), nullable=False),
    sa.Column('ceiling', sa.Integer(), nullable=False),
    sa.Column('ceiling_eo', sa.Integer(), nullable=True),
    sa.Column('takeoff_distance', sa.Integer(), nullable=False),
    sa.Column('landing_distance', sa.Integer(), nullable=False),
    sa.Column('takeoff_distance_50', sa.Integer(), nullable=False),
    sa.Column('landing_distance_50', sa.Integer(), nullable=False),
    sa.Column('gross_weight', sa.Integer(), nullable=False),
    sa.Column('empty_weight', sa.Integer(), nullable=False),
    sa.Column('max_payload', sa.Integer(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('rate_of_climb', sa.Integer(), nullable=False),
    sa.Column('rate_of_climb_eo', sa.Integer(), nullable=True),
    sa.Column('has_autopilot', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('engine_manufacturer', sa.String(length=80), nullable=False),
    sa.Column('engine_model', sa.String(length=80), nullable=False),
    sa.Column('engine_hp', sa.Integer(), nullable=False),
    sa.Column('engine_tbo', sa.Integer(), nullable=False),
    sa.Column('engine_tbo_years', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engines')
    op.drop_table('models')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
